-- NEST AUTH USER SETUP
--
-- Run this file only as a reference in the Supabase SQL Editor.
-- Supabase Auth users should normally be created from:
-- Authentication -> Users -> Add user
--
-- The database trigger in supabase/schema/00_initial_schema.sql automatically
-- creates public.users after an auth user is created.
--
-- After creating users in the dashboard, copy their UUIDs into:
-- supabase/seed/02_users_and_groups.sql
--
-- Recommended users:
-- coordinator@nest.edu  -> role: coordinator
-- student1@nest.edu      -> role: student
-- student2@nest.edu      -> role: student
-- student3@nest.edu      -> role: student
-- student4@nest.edu      -> role: student

-- Promote a user to coordinator after replacing the UUID:
-- UPDATE public.users
-- SET role = 'coordinator', full_name = 'Course Coordinator'
-- WHERE id = 'AUTH_USER_UUID_HERE';

-- Update student profile data after replacing the UUID:
-- UPDATE public.users
-- SET full_name = 'Student Name',
--     student_registration_number = 'CS2025001',
--     whatsapp_phone = '+254700000000',
--     course = 'CS101'
-- WHERE id = 'AUTH_USER_UUID_HERE';
